
<form id="newArticle" action="add_article.php" method="POST">
     <!-- Groupe de champs encadré par bordure avec un titre -->
    <fieldset>

        <legend><i class="far fa-file-alt"></i> Nouvel article</legend>

        <ul>
            <li>
                <label for="articleTitle">Titre :</label><br/>
                <input type="text" id="articleTitle" name="articleTitle">
            </li>
            <li>
                <label class="textarea" for="articleContent">Article :</label><br/>
                <textarea id="articleContent" name="articleContent" rows="10"></textarea>
            </li>

            <li>
                <label for="articleAuthor">Auteur :</label><br/>
                <select name="articleAuthor">
                    <?php foreach ($authors as $author): ?>
                        <!-- prends Id correspondant pour pouvoir le récup plus tard sans avoir à regarder contenu -->
                        <option value="<?= ($author['Id']) ?>">
                            <?= htmlspecialchars($author['FirstName']) ?> 
                            <?= htmlspecialchars($author['LastName']) ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>

            <li>
                <label for="articleCategory">Catégorie :</label><br/>
                    <select name="articleCategory">
                    <?php foreach ($categories as $category): ?>
                        <!-- prends Id correspondant pour pouvoir le récup plus tard sans avoir à regarder contenu -->
                        <option value="<?= ($category['Id']) ?>">
                            <?= htmlspecialchars($category['Name']) ?>
                        </option>
                    <?php endforeach ?>
                    </select>
            </li>

            <li id="liButtons">
                <button class="button button-primary" type="submit">Enregistrer</button>

                <button class="button button-secondary" type="reset">Effacer</button>

                <a class="button button-cancel" href="admin.php"><input type="button" value="Annuler" /></a>

            </li>

        </ul>

    </fieldset>

</form>